### ISSUE TITLE
Not working with Flutter 1.15 (master channel): TextOneLine is missing implementations.

### ISSUE THREAD

**Issue by Amir-P** [marcglasberg/assorted_layout_widgets#1]
Using `assorted_layout_widgets: ^1.0.15` and `sdk: ">=2.3.0 <3.0.0"` I'm getting this error when I've added `RowSuper` to a widget:

```
Compiler message:
../../../flutter/.pub-cache/hosted/pub.dartlang.org/assorted_layout_widgets-1.0.15/lib/src/text_one_line.dart:19:7: Error: The non-abstract class 'TextOneLine' is missing implementations for these members:
 - Text.textHeightBehavior
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class TextOneLine extends StatelessWidget implements Text {
      ^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/text.dart:432:31: Context: 'Text.textHeightBehavior' is defined here.
  final ui.TextHeightBehavior textHeightBehavior;
                              ^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/assorted_layout_widgets-1.0.15/lib/src/text_one_line.dart:200:7: Error: The non-abstract class 'RenderParagraphX' is missing implementations for these members:
 - RenderParagraph.textHeightBehavior
 - RenderParagraph.textHeightBehavior=
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RenderParagraphX extends RenderBox
      ^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/paragraph.dart:281:29: Context: 'RenderParagraph.textHeightBehavior' is defined here.
  ui.TextHeightBehavior get textHeightBehavior => _textPainter.textHeightBehavior;
                            ^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/paragraph.dart:282:7: Context: 'RenderParagraph.textHeightBehavior=' is defined here.
  set textHeightBehavior(ui.TextHeightBehavior value) {
      ^^^^^^^^^^^^^^^^^^
```

**Comment by marcglasberg** [comment]
Please provide your `flutter doctor`.

**Comment by Amir-P** [comment]
Here is `flutter doctor` output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.7-pre.83, on Mac OS X 10.15.2 19C57, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by marcglasberg** [comment]
@Amir-P The problem is that you are not in the stable channel (currently v1.12.13+hotfix.8). 

In the master channel (the one you are in: v1.14.7-pre.83) the `Text` widget has been modified. They have added `Text.textHeightBehavior`, which didn't exist before.

When that version becomes stable I will add this property, but for now I can't fix this, because it would stop working in the stable channel.

**Comment by marcglasberg** [comment]
Until 1.15 becomes stable you can point to Pascal's repo. It should work if they add this to their pubspec.yaml:

  assorted_layout_widgets:
    git: https://github.com/passsy/assorted_layout_widgets.git
    ref: 25c111e556b3d69eed203ebd3a54740d9044c4e3

Just don't forget to go back to the main repo when 1.15 becomes stable.

**Comment by Amir-P** [comment]
Thanks I moved to stable channel and everything is ok now

**Comment by esDotDev** [comment]
I'm geting an error that the `ref` keyword is not allowed with the above snippet. Latest master.

**Comment by marcglasberg** [comment]
@esDotDev Have you tried pointing to Pascal Welsch's repo, as explained above?

**Comment by PedroRTomas** [comment]
Hi,
I'm facing similar problems, but I'm currently pointing to beta branch.
Here is my flutter doctor:
![flutter_doctor](https://user-images.githubusercontent.com/48090914/80512822-00282a80-8976-11ea-8d00-ebdb9e8bf3f7.JPG)

The output of gradle:
![error_super_column0](https://user-images.githubusercontent.com/48090914/80512887-1d5cf900-8976-11ea-8efc-d6366432af78.jpg)
![error_super_column1](https://user-images.githubusercontent.com/48090914/80512889-1df58f80-8976-11ea-9a6e-4754e42a292c.jpg)

Note: I've tried to change the branch to stable, however, due to other dependencies being used, I've got tons of errors.

**Comment by marcglasberg** [comment]
@PedroRTomas Have you tried pointing to Pascal Welsch's repo, as explained above?

**Comment by PedroRTomas** [comment]
@marcglasberg Those are great news! I haven't tried to point to Pascal Welsch's repo, because I'm working in a team (Colleague Project) and I don't have the authority to make that kind of change.

**Comment by marcglasberg** [comment]
@PedroRTomas Another solution is going to Pascal's repo and just copying the file that contains that widget. Put that file into your own project, and import it. Hide the one from assorted_layout_widgets. Then after the upgrade is made, simply remove the copied file from your project.

**Comment by marcglasberg** [comment]
It should now work for version: 1.1.0 (Flutter 1.17);
