### ISSUE TITLE
RowSuper flex

### ISSUE THREAD

**Issue by spixy** [marcglasberg/assorted_layout_widgets#13]
Hi!
`RowSuper` has `fill` attribute which affects all children of the row.
I would like to fill all remaining space by only one last child.
I have tried using `Expanded`, `SizedBox.expand` or `Container(width: double.infinity)` bot none of them worked.
Is it possible?

**Comment by marcglasberg** [comment]
No, sorry. Despite the name, a `RowSuper` is not a real `Row`. It's a completely different widget that's not trying to emulate a real `Row`. The `Expanded` only makes sense inside a real `Row`. I'd suggest you should maybe try using a `Row` instead of a RowSuper in this specific case.
