### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by jielundewode** [marcglasberg/assorted_layout_widgets#21]
build msg is：
pub-cache/hosted/pub.dartlang.org/assorted_layout_widgets-6.0.0/lib/src/delayed.dart:40:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                            ^^^^^^^^^^^^^^^^^^^^

pls fix it

**Comment by marcglasberg** [comment]
You are probably using version `6.0.0` with `Flutter 2.x`.

To fix this:

- Upgrade your app to Flutter 3.0; or

- Fix the package version in your `pubspec.yaml`, like so:
    `  assorted_layout_widgets: 5.8.5`
