### ISSUE TITLE
When using TextOneLine, we found all kinds of strange unicode characters when inspecting our app in appium.

### ISSUE THREAD

**Issue by dickverweij** [marcglasberg/assorted_layout_widgets#24]
When inspecting the code for  TextOneLine we saw this:

` String? get data => super.data == null ? null : Characters(super.data!).toList().join("\u{200B}");`

why is that?

**Comment by marcglasberg** [comment]
It's adding zero-width spaces between all charactes. This will force the text to be displayed in a single line. 

Please see: https://github.com/flutter/flutter/issues/18761

Keep in mind this widget is a temporary hack. It will be deprecated when Flutter fixes this issue.
