### ISSUE TITLE
TextField in RowSuper

### ISSUE THREAD

**Issue by fehernyul** [marcglasberg/assorted_layout_widgets#25]
Hi,
When I'm putting 2 TextField in a RowSuper, and start to type to one of TextField, the aspect of 2 TextFiel was changed. Now its not 50%/50%, but 70/30, 80/20, ...
The more I write into one of them than the other, it takes up more space.

How can I prevent this?

My target is the 2 TextField stays 50%50% ratio as original.

![image](https://user-images.githubusercontent.com/25593792/213438369-f089dfde-9aed-4760-bfe8-36e664c9eb90.png)
![image](https://user-images.githubusercontent.com/25593792/213438422-df096220-776b-42ab-bb09-70e2b9edda03.png)

Thanks,
Gabor

**Comment by marcglasberg** [comment]
I suggest in this case you should use a native `Row`:

```
Row(children: [Expanded(child: textfield1), Expanded(child: textfield1), ]);
```

There is no need to use `RowSuper` in this case. `RowSuper` is not a general purpose row. It's meant to be used in some specific use cases that the native `Row` does not work well.
