### ISSUE TITLE
FitHorizontally division by zero with shrinkLimit: 0.0

### ISSUE THREAD

**Issue by passsy** [marcglasberg/assorted_layout_widgets#3]
This combination results in a division by zero

```dart
FitHorizontally(
  fitsHeight: false,
  shrinkLimit: 0.0,
  child: //...
)
```

https://github.com/marcglasberg/assorted_layout_widgets/blob/c0e1a25b07dc7d4cdf1a6d5d5b61d1388b41108e/lib/src/fit_horizontally.dart#L191-L192

**Comment by marcglasberg** [comment]
Fixed: version 1.1.3.
