### ISSUE TITLE
Gestures behaving in unexpected ways when the SuperColumn has invert set to true.

### ISSUE THREAD

**Issue by temcewen** [marcglasberg/assorted_layout_widgets#35]
When you have a SuperColumn that has invert set to true, even though the first widgets in the list will be visually on top of the subsequent widgets, the widgets in the back (visually) will receive the gestures instead. For my purposes, this makes the SuperColumn practically useless as they create really unintuitive, weird user experiences when used in combination with the invert property.

**Comment by temcewen** [comment]
To note, I didn't test the SuperRow, this may only be a problem with the SuperColumn, I am unsure.

**Comment by marcglasberg** [comment]
Thanks, this needs to be fixed.

**Comment by temcewen** [comment]
@marcglasberg thanks for maintaining this. If you ping me when you get a fix out, I'll make sure to give it a test run again!

**Comment by temcewen** [comment]
@marcglasberg I just got around to testing this, and it works like a charm! Thanks for supporting this package!
