### ISSUE TITLE
TextOneLine doesn't respect OS-set textScaleFactor

### ISSUE THREAD

**Issue by erickok** [marcglasberg/assorted_layout_widgets#4]
First off, thanks for your work. It is useful and well done. 👍 

A minor thing: We found that using `TextOneLine` it does not automatically apply the OS-set `textScaleFactor` the way that a normal `Text` does. It you set the iOS or Android accessibility text scale to something larger (or smaller) than the default, the text stays the same size.

Explicitly setting it scale factor with `textScaleFactor: MediaQuery.of(context).textScaleFactor` works well, which is great, but we expected this to be applied by default.

**Comment by marcglasberg** [comment]
It should now work as expected, for version: 1.1.0 (Flutter 1.17)

**Comment by erickok** [comment]
Can confirm this is fixed. 👍
